# Generated by Django 3.2 on 2023-04-18 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20230418_0750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.DeleteModel(
            name='Following',
        ),
    ]
